version: "1.0"
name: build-apk
displayName: 构建Android APK
stages:
- name: build
  displayName: 构建APK
  strategy: naturally
  trigger: auto
  steps:
  - step: build@python
    name: ""
    displayName: 构建APK
    pythonVersion: '3.11'
    commands:
    - |
      set -ex
      mkdir -p /usr/share/man/man1/
      apt-get update
      apt-get install -y --fix-broken autoconf automake libtool pkg-config cmake libssl-dev libffi-dev libltdl-dev libncurses5-dev openjdk-17-jdk ccache zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget unzip git
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      export PATH="$JAVA_HOME/bin:$PATH:$HOME/.local/bin"
      pip install --user buildozer 'cython<3.0'
      mkdir -p fonts
      curl -sL -o fonts/NotoSansSC-Regular.otf 'https://cdn.jsdelivr.net/gh/notofonts/noto-cjk@main/Sans/OTF/SimplifiedChinese/NotoSansSC-Regular.otf' || true
      buildozer android debug
    artifacts:
    - name: APK
      path:
      - bin
      type: .tar.gz
    caches:
    - "~/.cache/pip"
    - "~/.buildozer"
    notify: []
    strategy:
      retry: "0"
      resource:
        cpu: "4"
        memory: "8"
triggers:
  trigger: auto
  push:
    branches:
      prefix:
      - main
notify: []
strategy:
  blocking: false
