version: "1.0"
name: build-apk
displayName: 构建Android APK
stages:
- name: build
  displayName: 构建APK
  strategy: naturally
  trigger: auto
  steps:
  - step: build@python
    name: ""
    displayName: 构建APK
    pythonVersion: '3.11'
    commands:
    - bash build.sh
    artifacts:
    - name: APK
      path:
      - bin
      type: .tar.gz
    caches:
    - "~/.cache/pip"
    - "~/.buildozer"
    notify: []
    strategy:
      retry: "0"
      resource:
        cpu: "4"
        memory: "8"
triggers:
  trigger: auto
  push:
    branches:
      prefix:
      - main
notify: []
strategy:
  blocking: false
